site_name: Vaccine Cold Chain Monitoring
repo_url: https://github.ibm.com/vaccine-cold-chain/vaccine-cold-chain-main.git
nav:
  - Solution Anatomy:
      - Vaccine manager microservice: infuse/vaccine-mgr.md
      - Container manager microservice: infuse/container-mgr.md
      - Cold Chain monitoring agent app with cloud pak for application: infuse/dev-scoring.md
 
      
  - Devops: 
    - Build and run the solution on Openshift: infuse/build-run.md
 

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences