site_name: Vaccine Cold Chain Monitoring
repo_url: https://github.ibm.com/vaccine-cold-chain/vaccine-cold-chain-main.git
nav:
  - Solution Anatomy:
      - Vaccine manager microservice: infuse/vaccine-mgr.md
      - Container manager microservice: infuse/container-mgr.md
      - Cold Chain monitoring agent app with cloud pak for application: infuse/dev-scoring.md
      - Engineer dispatching with Business process with Cloud Pak for Automation: bpm/readme.md
      - IoT Simulator: infuse/simul-app.md
      - Collect data with Cloud Pak for Data: collect/cp4d-collect-data.md
      - Define the anomaly detection scoring model with Watson Studio: analyze/ws-ml-dev.md
  - Devops: 
    - Build and run the solution on Openshift: infuse/build-run.md
  - Multi-cloud management:
    - Problem statement: mcm/problem.md
    - Deploy dependant products: mcm/deploy-products.md
    - Deploy solution: mcm/deploy-solution.md
  - Compendium: compendium.md

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences